### ISSUE TITLE
'createBotField' method could send a field value but is not implemented.

### ISSUE THREAD

**Issue by juanbenitez** [manychat/manychat-api-php#15]
According to the docs we are able to send a value when creating a new bot field using the 'createBotField' method; but is not implemented right now.
Are you accepting PRs?

**Comment by gavyur** [comment]
¡Hola Juan!

Thank you for noticing that problem, value parameter has been added in [v1.0.5](https://github.com/manychat/manychat-api-php/releases/tag/v1.0.5) release.

Yes, we are accepting PRs.

**Comment by juanbenitez** [comment]
Awesome thanks!
